[package]
name = "real-cugan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.candle-core]
git = "https://github.com/huggingface/candle.git"
version = "0.3.2"
features = ["cuda"]

[dependencies.candle-nn]
git = "https://github.com/huggingface/candle.git"
version = "0.3.2"
